package org.springboot.sample.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sum_score
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    private String sumScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.avg_score
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    private String avgScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sum_score
     *
     * @return the value of student.sum_score
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public String getSumScore() {
        return sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sum_score
     *
     * @param sumScore the value for student.sum_score
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public void setSumScore(String sumScore) {
        this.sumScore = sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.avg_score
     *
     * @return the value of student.avg_score
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public String getAvgScore() {
        return avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.avg_score
     *
     * @param avgScore the value for student.avg_score
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public void setAvgScore(String avgScore) {
        this.avgScore = avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbggenerated Tue Aug 16 15:48:49 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}